### ISSUE TITLE
Something wrong when "z80-asm-meter.syntax.label" is set to "colonOptional"

### ISSUE THREAD

**Issue by Tolik-Trek** [theNestruo/z80-asm-meter-vscode#100]
Hi!
Incorrect behavior in my project.
It only shows information on the line that has the label.
Ver. 3.4.1 works great. 3.4.2 and 3.5.0 not(((
<img width="601" alt="nothing" src="https://user-images.githubusercontent.com/85737314/219867723-c373253f-b007-4338-88f8-4d0ed970cbf2.png">
<img width="588" alt="something" src="https://user-images.githubusercontent.com/85737314/219867727-4b8658a4-f236-498a-97e2-854c415a97ba.png">
[Asmconv2.zip](https://github.com/theNestruo/z80-asm-meter-vscode/files/10774299/Asmconv2.zip)

**Comment by theNestruo** [comment]
Ooops! Sorry!
You are right; there is something wrong when `"z80-asm-meter.syntax.label": "colonOptional"`

**Comment by theNestruo** [comment]
Fixed and released the 3.5.1 version (https://github.com/theNestruo/z80-asm-meter-vscode/releases/tag/3.5.1).
It seems to be already available in the Visual Studio Marketplace, so you should receive the updated soon.
Please let me know if it fixes the issue (and also let me know if it created more issues, of course!)
Thanks for the report!

**Comment by Tolik-Trek** [comment]
Big thanks)))
