### ISSUE TITLE
Incorrect byte counting with ";"

### ISSUE THREAD

**Issue by Tolik-Trek** [theNestruo/z80-asm-meter-vscode#105]
Hi.

 DB   #00,"a","s","d","f","g","h","j","k","l",";","'",#0D  ; 1 byte
 DB   #00,"a","s","d","f","g","h","j","k","l",';',"'",#0D    ; 11 bytes

Actually the size is 13 bytes.

**Comment by theNestruo** [comment]
Fixed and released the 3.5.2 version (https://github.com/theNestruo/z80-asm-meter-vscode/releases/tag/3.5.2).
You should receive the updated soon; please let me know if any other issue arises.
Thanks you very much for reporting!
