### ISSUE TITLE
Feature Request: Implement support for DeZog debug adapter

### ISSUE THREAD

**Issue by kborowinski** [theNestruo/z80-asm-meter-vscode#11]
Would be it possible to add support for [DeZog Z80 Debugger](https://github.com/maziac/DeZog)?

**Comment by theNestruo** [comment]
Yes? (I'm not sure what are you requesting) How is DeZog debug adapter not supported by this extension right now?

**Comment by kborowinski** [comment]
Well, I have latest version of DeZog and z80-asm-meter installed on VSC and I don't get clock cycles and bytecode size:

![z80-assembly-meter](https://user-images.githubusercontent.com/16168755/73989280-933c6000-4945-11ea-99dd-c4a3f1f15a2b.gif)

**Comment by theNestruo** [comment]
Oh, I see!
DeZog seems to use [`asm-collection`](https://github.com/maziac/DeZog/blob/master/package.json#L99) as its language ID. Try adding it to the `z80-asm-meter.languageIds` setting of this extension:
```
    "z80-asm-meter.languageIds": [
        "asm-collection",
        "z80-macroasm",
        "z80-asm",
        "z80",
        "pasmo"
    ]
```

**Comment by kborowinski** [comment]
Thanks, it works now! 

![image](https://user-images.githubusercontent.com/16168755/74026092-ac74f900-49a5-11ea-9262-6eaea5c2d3cc.png)

BTW, what are the "</>" for?

**Comment by theNestruo** [comment]
Just the `$(code)` [icon](https://microsoft.github.io/vscode-codicons/dist/codicon.html) to decorate the size; similar to the `$(watch)` icon decorating the timing. Not the best choice, probably. Would `$(file-code)` be clearer?

**Comment by kborowinski** [comment]
Go with `$(file-code)`, it's better.

**Comment by theNestruo** [comment]
Next version will use that icon :)
Thanks!
