### ISSUE TITLE
ex af,af' with comment does not show instruction ts

### ISSUE THREAD

**Issue by inchl** [theNestruo/z80-asm-meter-vscode#112]
ex af,af' ; this comment causes the ts not shown

probably something to do with the trailing ' in ex af,af'

**Comment by cardosojoao** [comment]
use only ex af,af no need for the ['}

**Comment by inchl** [comment]
nope... if I do not put the ' the opcode is not recognized, causing no ts shown

**Comment by theNestruo** [comment]
It seems that it got broken when I fixed the issue #107. Sorry for the inconvenience. And thanks for reporting!
