### ISSUE TITLE
Feature request: Add support for Z80N instructions

### ISSUE THREAD

**Issue by kborowinski** [theNestruo/z80-asm-meter-vscode#12]
Z80N in ZX Spectrum Next [introduced several new instructions](https://wiki.specnext.dev/Extended_Z80_instruction_set) (all with **E** in *Status* column). Would you be willing to support them in your extension?

**Comment by theNestruo** [comment]
Not in my roadmap (for the reasons explained in #9), sorry.

But please check [Maziac](https://github.com/maziac)'s [Z80 Instruction Set](https://github.com/maziac/z80-instruction-set) extension as it may fit your needs.

**Comment by theNestruo** [comment]
Z80N support added. Thanks for your pull request!
