### ISSUE TITLE
feature request to support not-flags

### ISSUE THREAD

**Issue by inchl** [theNestruo/z80-asm-meter-vscode#123]
Hi,

Is it possible to add support for a not-operator for flags? I would like to do:
jp nz,label, but also jp !z,label

This currently is supported by the Glass compiler, but not recognized by the z80 meter.

Stephan

**Comment by inchl** [comment]
same goes for:
PE == !PO
PO == !PE
C == !NC
NC == !C
Z == !NZ
NZ == !Z
M == !P
P == !M

:-)

**Comment by theNestruo** [comment]
Also, repeat block syntax in Glass is slightly different from SjASMPlus; I'll add it as a part of the Glass assembler syntax support

**Comment by theNestruo** [comment]
Glass Z80 assembler syntax support added un 4.2.0.

Please review the following settings:

- ~~`z80-asm-meter.sjasmplus`~~: Deprecated. Set "z80-asm-meter.syntax" to "sjasmplus" instead.
- `z80-asm-meter.syntax`: Adjusts the main syntax of the assembler:
    - (...)
    - `glass`: Enables support for parsing [Glass Z80 assembler](http://www.grauw.nl/projects/glass/) syntax.
