### ISSUE TITLE
custom added [ts=...] is not a instruction

### ISSUE THREAD

**Issue by inchl** [theNestruo/z80-asm-meter-vscode#132]
The following code causes a different presentation of the timing (just userinterface, timing ok). When a textblock is selected including the [ts=12] the jp is not detected as the last instruction.

jp nz,label      ; [ts=12]

**Comment by theNestruo** [comment]
Hi!

I'm trying to reproduce the problem using the following settings:
```json
  "z80-asm-meter.timings.mode": "all",
  "z80-asm-meter.timings.threshold": 1,
  "z80-asm-meter.timings.hints": "any",
```

But I get the same presentation with and without the timing hint:
![image](https://github.com/theNestruo/z80-asm-meter-vscode/assets/12213477/67120228-50bd-4a11-bbaf-3bf2552edf5b)
![image](https://github.com/theNestruo/z80-asm-meter-vscode/assets/12213477/dfd2b618-b731-4304-8efa-490e854475a0)
![image](https://github.com/theNestruo/z80-asm-meter-vscode/assets/12213477/74b6f462-3dd3-4dd7-8e05-bb053ac3945c)
![image](https://github.com/theNestruo/z80-asm-meter-vscode/assets/12213477/601bc6f6-f4f8-4bf9-91f0-5d24e49dfc0e)

Please note that, when different timing modes yield the same values (11, in the version without timing hints), the value is only presented once, with both icons in front of that value.

**Comment by inchl** [comment]
Have been AFK but I will test it again using your latest version.

**Comment by inchl** [comment]
Not an issue anymore... I did not used the last version

**Comment by theNestruo** [comment]
Ok! I'll close the issue, then
