### ISSUE TITLE
not-flags no longer working

### ISSUE THREAD

**Issue by inchl** [theNestruo/z80-asm-meter-vscode#133]
This issue had been resolved, but is no longer working

jp !nz,label

**Comment by theNestruo** [comment]
Hi!

Do you have `"z80-asm-meter.syntax": "glass"` in your settings?

I plan on simplifying the configuration of the extension in the next major release; it started being a rather simple extension, but growth hasn't scalated well on the settings side :/

**Comment by inchl** [comment]
I changed it to glass, and now its seems to work
