### ISSUE TITLE
opcode starting with semicolon should ignore customized ts

### ISSUE THREAD

**Issue by inchl** [theNestruo/z80-asm-meter-vscode#144]
`;call	test ; [ts=1011]`

this should be measured a 0

**Comment by theNestruo** [comment]
No, that's incorrect.

I guess you have `"z80-asm-meter.timings.hints": "any"`:

> - `z80-asm-meter.timings.hints`: Enables timing hints, read from the line comment. (...)
>   - `any`: Any timing hint will be added. This includes empty (i.e.: no actual source code) lines.

With that configuration, `;call test ; [ts=1011]` is just an empty line with a comment with a timing hint. There is no difference from `; [ts=1011]` or `; any text ; [ts=1011]`, and those line has timing hints should be taken into account when `"z80-asm-meter.timings.hints": "any"`.

**Comment by theNestruo** [comment]
...but I think I can do something to detect commented out code. Let me give it a try.

**Comment by theNestruo** [comment]
Released to marketplace (as I did a mistake and already published the 5.0.0 wihtout the _pre-release_ check).

Set `z80-asm-meter.timing.hints.enabled` to `ignoreCommentedOut`
