### ISSUE TITLE
Behaves the opposite way

### ISSUE THREAD

**Issue by Tolik-Trek** [theNestruo/z80-asm-meter-vscode#150]
Hi!
Something strange...
It counts clock cycles and bytes for commented instructions, but does not do its job for uncommented instructions.
MacOS Sonoma v14.2
Visual Studio Code v1.83.1
Z80 Assembly meter v5.2.0

<img width="533" alt="image" src="https://github.com/theNestruo/z80-asm-meter-vscode/assets/85737314/59f7d746-a286-45e0-b17a-11723ba910f4">

<img width="463" alt="image" src="https://github.com/theNestruo/z80-asm-meter-vscode/assets/85737314/5bbf342d-34ef-4fb7-841e-cf21c11b5525">

**Comment by theNestruo** [comment]
Sorry!
Can you please share your configuration?

**Comment by Tolik-Trek** [comment]
Tried with default settings. MacOS beta may be to blame.

**Comment by theNestruo** [comment]
Hm... would you mind uninstalling and reinstalling the extension? (a blind guess)
If you are using the default settings, the version 5.2.0 should appear on the right side of the status bar (so I'm not sure your version is really v5.2.0)

**Comment by Tolik-Trek** [comment]
I tried with the default settings and my own, the result is the same. I deleted the settings and reinstalled.

**Comment by theNestruo** [comment]
The only fragment of code that involves detecting commented out code is when `"z80-asm-meter.timing.hints.enabled": "ignoreCommentedOut"`... but that is for timing hints, not for actual z80 code.

Another possibility I can think of is that your status bar is not being updated properly and you are seeing old meterings. I mean: you change the selection, but the status bar keeps showing the previous selection... But I doubt this is your case unless the extension is giving a metering, then always failing internally afterwards. And that is an unlikely scenario.

To be honest, I don't know what is really happening, and I cannot reproduce the issue :(

Would you mind manually installing a [nigthly build](https://github.com/theNestruo/z80-asm-meter-vscode/actions/workflows/npmci.yml) (such as: [z80-asm-meter-5.3.0-nightly](https://github.com/theNestruo/z80-asm-meter-vscode/suites/17711141559/artifacts/1013895374)) to see if the problem still happens?

**Comment by Tolik-Trek** [comment]
Versions 4.x.x works fine. 5.x.x don't work fine)))
Nigthly build don't work.
Version 5.0.0:
https://github.com/theNestruo/z80-asm-meter-vscode/assets/85737314/0ada546e-ba93-4ea4-aa39-501743e6ba9e

**Comment by theNestruo** [comment]
Good news! I have found the culprit: `"z80-asm-meter.syntax": "pasmo"` (or, more precisely, `"z80-asm-meter.syntax.label.colonOptional": true`, implied by "pasmo").
I'll try to fix it this evening.

**Comment by Tolik-Trek** [comment]
v5.2.0

https://github.com/theNestruo/z80-asm-meter-vscode/assets/85737314/55553195-58b2-4d83-8c8c-6cc4a47444a1

**Comment by theNestruo** [comment]
That was totally unexpected; I scarcely use the UI version of the settings, so that behaviour went completely unnoticed.

I'll take a look a it too! Sorry!

**Comment by theNestruo** [comment]
Hi!
I'm publishing v5.3.0 just now. It should solve the original issue.

For the Settings UI issue, I'll try to make a minimal example as I think it is a bug in VS Code. It can be worked around if I rename the `z80-asm-meter.syntax` settings... but I prefer to check if they can solve the issue on their side first.

For the moment, could you configure your extensing using the Settings (JSON) (instead of the UI)?

**Comment by theNestruo** [comment]
Hi!
Publishing v5.3.1 that fixes the checkboxes issues in settings UI.
Thank you for the detailed report. I hope everything works as expected now!
If anything else is amiss, don't hesitate to open a new issue ^_^

**Comment by Tolik-Trek** [comment]
> Hi! Publishing v5.3.1 that fixes the checkboxes issues in settings UI. Thank you for the detailed report. I hope everything works as expected now! If anything else is amiss, don't hesitate to open a new issue ^_^

Perfect! Everything works great! Thanks a lot))))
