### ISSUE TITLE
Is user-defined working correctly?

### ISSUE THREAD

**Issue by bengalack** [theNestruo/z80-asm-meter-vscode#156]
I haven't updated in a while, but now, when I did (v5.3.3), I can't get the msx cost of macros to show. See image:

![image](https://github.com/theNestruo/z80-asm-meter-vscode/assets/10129101/5ac3c630-76cb-4702-8aec-0a2e9e08675a)

Note that the size works fine. I tried without quotes on the msx-cost as well, but no success.

Any hints?

**Comment by theNestruo** [comment]
> Any hints?

Hint: update to the version 5.3.4 I have just published :)

Jokes aside, it was a bug on my side; nothing wrong in your configuration.

Sorry for the inconvenience. And thanks for reporting!
