### ISSUE TITLE
outcommented line still shows and measures timing

### ISSUE THREAD

**Issue by inchl** [theNestruo/z80-asm-meter-vscode#170]
The following line is measured as 18, but since it's commented out I expected it to be blank (not measured)
;_sync:			call	test

When a space is placed before the ; the behaviour is as expected (not showing/measuring timing). Problem only appears to happen when the ; is the first chr of the line.

using version: 5.6.0 (preview)

Stephan

**Comment by theNestruo** [comment]
The parser is considering ";_sync" as a label.
I'll fix it as soon as possible.

**Comment by theNestruo** [comment]
New version (5.6.1, preview) contains the fix for this issue. Thanks for reporting!
