### ISSUE TITLE
Add support for asz80

### ISSUE THREAD

**Issue by aoineko-fr** [theNestruo/z80-asm-meter-vscode#179]
Hi,

Nowadays, C programmers that create MSX games are often using SDCC tool-chain (through MSXgl or Fusion-C library for example) and have to deal with asz80 assembler syntax (either in separate assembler file or by including assembler code in C using `__asm` and `__endasm` directive).

It would be great if this super-useful extension could be compatible with asz80 syntax.
Syntax is described here: https://shop-pdp.net/ashtml/asmlnk.htm

Best regards,

**Comment by theNestruo** [comment]
It already is (see https://github.com/theNestruo/z80-asm-meter-vscode/issues/33).

Maybe not all its syntax is correcly covered. Is there any particular source code block that the extension is failing to meter?

**Comment by aoineko-fr** [comment]
What "syntax" option should we use for asz80?

**Comment by theNestruo** [comment]
Try with `default`

**Comment by aoineko-fr** [comment]
Since the other syntaxes have an option, I thought that asz80 shouldn't work without its own.
But 'default' works fine. 👌

I added _Z80 Assembly meter_ as recommended VS Code extension for developing with MSXgl:
https://aoineko.org/msxgl/index.php?title=VS_Code

Thanks,
