### ISSUE TITLE
Unable to install on VSCodium

### ISSUE THREAD

**Issue by TimRegeant** [theNestruo/z80-asm-meter-vscode#182]
Can support be added for VSCodium? I get the following message trying to install the extension.

Error: Unable to install extension 'thenestruo.z80-asm-meter' as it is not compatible with VSCodium '1.93.1'.

**Comment by theNestruo** [comment]
I am not familiar with VS Codium, but the extension doesn't have anything special that could cause a problem with VS Codium.

The "1.93.x" rings a bell... I'm using dependabot to keep third party versions up to date, and that includes "vscode", so maybe the latest version is tied to the (currently) latest version of VS Code (1.94.x).

```json
  "engines": {
    "vscode": "^1.94.0"
  },
```

Please try updating your VS Codium to a 1.94.x, or try installing an older version of the extension. Let me know if that solves the issue.

**Comment by TimRegeant** [comment]
Thank you, issue is resolved after upgrading to 1.94.x
