### ISSUE TITLE
Not working with VSCode 1.43.2

### ISSUE THREAD

**Issue by Duefectu** [theNestruo/z80-asm-meter-vscode#20]
VSCode 1.43.2
z80-asm-meter 1.0.1

The lower status bar does not display any information.
I'm trying it with .asm and .z80 files, and under no circumstances does it show information.
I selected code like :
        ld hl,16384
        ld (hl),a
        inc hl

I'm using DeZog, ASM Code Lens, Z80 Instruction Set and Z80 Unit test. But I disabled it to test with no results.

**Comment by theNestruo** [comment]
It seems the same problem as #11.

DeZog seems to use `asm-collection` as its language ID. Try adding it to the `z80-asm-meter.languageIds` setting of this extension:

```json
    "z80-asm-meter.languageIds": [
        "asm-collection",
        "z80-macroasm",
        "z80-asm",
        "z80",
        "pasmo"
    ]
```

That should do the trick. However, I'm not sure about the other extensions... Maybe one of them has a different language ID for `.asm` or `.z80` files. Please check the configured language (right side of the status bar) and language ID that your installation is using for the files, and append it to the `z80-asm-meter.languageIds` setting if it is not there already.

**Comment by theNestruo** [comment]
From version 1.1.0 onwards, DeZog language ID is included in the default configuration.
