### ISSUE TITLE
SjASMPlus Fake Instructions metter implementation needed

### ISSUE THREAD

**Issue by Dolphin101546015** [theNestruo/z80-asm-meter-vscode#65]
SjASMPlus have some convinient Fake Instructions like:
ld hl, de
sra hl
ldi (iy+nn),bc

Please made metter for all this instructions too, it will be so good!

List of all such instructions placed here:
https://z00m128.github.io/sjasmplus/documentation.html#s_fake_instructions

With best regards, Dolphin_Soft.

**Comment by theNestruo** [comment]
Hi, @Dolphin101546015 !

As I don't use SjASMPlus and its _sacrilegious_ syntax ;)... please help me test this nightly build (https://github.com/theNestruo/z80-asm-meter-vscode/suites/4345757316/artifacts/114000831) before I publish the new version.
I've checked pasted that list of instructions in one .asm file and everything looked fine, but I prefer a real SjASMPlus user testing it for a couple of days. Let me know if you find something wrong.

Don't forget you'll need to set `z80-asm-meter.sjasmplusFakeInstructions` to `true` in your settings.

Thank you!

**Comment by theNestruo** [comment]
I have published a new version that includes this change, so from 2.0.0 onwards the extension should meter the SjASMPlus fake instructions
