### ISSUE TITLE
Wrong opcodes for push/pop af

### ISSUE THREAD

**Issue by maziac** [theNestruo/z80-asm-meter-vscode#8]
Hi,
great tool. Just  installed it.

I found a small flaw though:
When I hover over "push af" I get a wrong opcode:
![Bildschirmfoto 2019-12-15 um 18 56 15](https://user-images.githubusercontent.com/3081973/70866678-dd6c1b00-1f6c-11ea-83a6-9dea940a5be2.jpg)

Should be "F5".

Same problem for "pop af". Should be "F1" instead of "1F".

**Comment by theNestruo** [comment]
Fixed! (There were some some typos in `z80InstructionSetRawData.ts`)

**Comment by maziac** [comment]
Verified. Is fixed.
