### ISSUE TITLE
Incorrect cycle/byte counting under some situations (SjASMPlus syntax)

### ISSUE THREAD

**Issue by sdsnatcher** [theNestruo/z80-asm-meter-vscode#99]
The cycle/byte counting feature reports incorrect results if any of the following features are present in the selected code:

- REPT/ENDR
- sjasmplus ".n" single-instruction repetition directives
- sjasmplus register lists  (i.e.: push af,bc,de)
- sjasmplus [temporary labels](https://z00m128.github.io/sjasmplus/documentation.html#s_temp_labels)

**Comment by theNestruo** [comment]
Hi, sdsnatcher.

I think I have already joked about SjASMPlus having a _sacrilegious_ syntax, so I will spare you the joke this time :)

#### REPT/ENDR

Yes, this is not supported at the moment.
It may take time to solve, as it requires a rewrite of the parser (that currently operates line by line), and support would be partial (would work with direct numerical expressions, but would not work with operations, symbolic constants, etc.)

#### sjasmplus ".n" single-instruction repetition directives

This should be supported by setting `"z80-asm-meter.syntax.repeat": "dot"`. Please let me know if that doesn't solve the issue.

#### sjasmplus register lists (i.e.: push af,bc,de)

Again, not supported at the moment.
...but it should be easier to solve than `REPT/ENDR`; I'll take a look at it for `PUSH/POP/INC/DEC` instructions only; I'll leave out `LD/ADD/SUB/...` (does anyone uses these?)

#### sjasmplus [temporary labels](https://z00m128.github.io/sjasmplus/documentation.html#s_temp_labels)

This should be supported by setting `"z80-asm-meter.syntax.label": "colonOptional"`. Please let me know if that doesn't solve the issue.

**Comment by theNestruo** [comment]
> **sjasmplus register lists (i.e.: push af,bc,de)**
> (...) I'll take a look at it for PUSH/POP/INC/DEC instructions only (...)
Implemented support for those.

**Comment by sdsnatcher** [comment]
> I think I have already joked about SjASMPlus having a _sacrilegious_ syntax, so I will spare you the joke this time :)

😅

But the new maintainers are doing a great job on cleaning such "eccentricities". Let's give them time.    😉


> #### REPT/ENDR
> Yes, this is not supported at the moment. It may take time to solve, as it requires a rewrite of the parser (that currently operates line by line), and support would be partial (would work with direct numerical expressions, but would not work with operations, symbolic constants, etc.)

Ok. But I've seen these to be frequently used on some projects, including msxsyssrc.

 
> #### sjasmplus ".n" single-instruction repetition directives
> This should be supported by setting `"z80-asm-meter.syntax.repeat": "dot"`. Please let me know if that doesn't solve the issue.

If I enable this option, the byte and cycle counter goes kaput. It counts some very low numbers, like 2 bytes.

 
> #### sjasmplus [temporary labels](https://z00m128.github.io/sjasmplus/documentation.html#s_temp_labels)
> This should be supported by setting `"z80-asm-meter.syntax.label": "colonOptional"`. Please let me know if that doesn't solve the issue.

This one seemed to help. I left it enabled.

**Comment by theNestruo** [comment]
> > #### sjasmplus ".n" single-instruction repetition directives
> > This should be supported by setting `"z80-asm-meter.syntax.repeat": "dot"`. Please let me know if that doesn't solve the issue.
> 
> If I enable this option, the byte and cycle counter goes kaput. It counts some very low numbers, like 2 bytes.

Fixed! Sorry for the inconvenience

**Comment by sdsnatcher** [comment]
No need to be sorry. I'm really grateful for this extension and your time to create it.   :)

**Comment by sdsnatcher** [comment]
BTW, I see that Github already has the v3.4.1 of this extension, while on VSCode only the 3.2.0 is available. How much time does it take for the newer version to appear on the VSCode extension repository?

**Comment by theNestruo** [comment]
I've uploaded 3.4.1 to Marketplace today and only takes a few minutes to be available there: https://marketplace.visualstudio.com/items?itemName=theNestruo.z80-asm-meter
Not sure why your installation is stuck in 3.2.0... Can you try uninstalling the extension and installing it again?

**Comment by theNestruo** [comment]
The interal code refactor that has been implemented for #114 has made possible to code `DUP/EDUP` or `REPT/ENDR` support.

**Comment by theNestruo** [comment]
Hi, @sdsnatcher

Please take a look at the latest release candidate of the next version: [3.6.0-RC4](https://github.com/theNestruo/z80-asm-meter-vscode/releases/tag/3.6.0-RC4) (it needs to be installed manually from the .vsix file).

Could you use this version a couple of days and tell me if `DUP`/`REPT` is working as expected and/or if something has gone amiss? Thanks!

**Comment by theNestruo** [comment]
Version 3.6.0 just published in the VS Code Marketplace!
